### ISSUE TITLE
Account balances, proposal deposit and voting power

### ISSUE THREAD

**Issue by tbruyelle** [atomone-hub/govgen#1]
The current distribution of govgen is based on the staked amount of accounts that voted NO or NWV on prop 848.

Considering that users will probably stake most of it to get voting power on govgen, this leaves very few tokens to activate proposals since the deposit is quite high (5000govgen at the time of writing).
Even the minimum deposit (currently 1% of the deposit) required just to submit the proposal may be an obstacle for users who have staked most of their balance.

We need to discuss whether this can be a problem or not.

**Comment by giunatale** [comment]
I think we can close this. We have had multiple discussions were we indirectly concluded that this is ok and it will require people to do thinks mindfully, but it's acceptable to have it this way without changes.

feel free to re-open if in disagreement.
