### ISSUE TITLE
Amino-json signing not compatible with cosmjs

### ISSUE THREAD

**Issue by tbruyelle** [atomone-hub/govgen#50]
PR #44 (shipped in version 1.0.3) changed the amino types path from `cosmos-sdk` to `govgen`. This sounded legitimate because `govgen.gov` is not the same module as `cosmos.gov`. Unfortunately, cosmjs is not aware of these new amino types and still generates them with the `cosmos-sdk` prefix, for instance when it needs to generate the bytes-to-sign for the amino-json signing mode (typically when a legder is used). This makes any ledger signature impossible, because the generated bytes-to-sign are differents between the client and the node.

Fortunately most (all?) Govgen validators are still running the govgen node using the version 1.0.1, where the amino types are not renamed. So today, cosmjs is able to sign a tx with a ledger for govgen, but things will stop to work as soon as validators will run version 1.0.3.

@clockworkgr Is there a way to tell cosmojs to use a different type name for amino-json encoding? I looked at their code and it seems to be set in stone. Look for instance at [`cosmos-sdk/MsgDeposit`](https://github.com/cosmos/cosmjs/blob/e819a1fc0e99a3e5320d8d6667a08d3b92e5e836/packages/stargate/src/modules/gov/aminomessages.ts#L91) (which should be `govgen/MsgDeposit` in govgen 1.0.3)

If compatibility with cosmjs can't be achieved, we should revert #44. The same change should be applied to the AtomOne gov module, and json-signer will also need to be updated.

**Comment by clockworkgr** [comment]
Simple fix but must ensure all are on 1.0.3....can't have 2 different versions of the same lib

**Comment by tbruyelle** [comment]
The place for the fix in cosmjs/telescope : https://github.com/atomone-hub/govgen-types/blob/main/scripts/codegen.js (thx @clockworkgr for the info)

But I don't think this needs to be changed now, as we are not going to update the govgen chain. But for AtomOne, where the amino types have been renamed similarly to govgen (but with `atomone` prefix), we'll have to update them.

For govgen, I think we need to remove/disable the v1.0.3 release, to ensure no validator will upgrade. #44 was a state breaking change, so it should have been shipped in a v1.1 release or something (cc @giunatale).

**Comment by tbruyelle** [comment]
Finally we decided to go with a new release that revert the change made in #44. So this issue is fixed by #51
