### ISSUE TITLE
feat(gov): refund text proposal deposit before the end of the voting period

### ISSUE THREAD

**Issue by tbruyelle** [atomone-hub/govgen#8]
## Problem Definition

Given that the voting period for text proposals is 365 days, such proposal depositors will have their funds locked during that time, preventing them from funding other proposals.

## Proposal

Refund text proposal deposits when a standard voting period has expired and the proposal is not vetoed. It might also be interesting to never actually end the voting period for such a proposal.

**Comment by giunatale** [comment]
I don't think we need this to be honest. It's ok for people to have their deposit indefinitely stuck for what it's worth

**Comment by tbruyelle** [comment]
After discussions during the [02/20 townhall](https://github.com/atomone-hub/genesis/blob/main/GovGen_Townhalls/Meeting4.md), the consensus is that this shouldn't be a problem.
